# Generated by Django 2.2.5 on 2020-08-17 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('publishtime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('userid', models.IntegerField(null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('visits', models.IntegerField(default=0)),
                ('thumbup', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('avatar', models.ImageField(max_length=500, null=True, upload_to='')),
                ('collected', models.BooleanField(default=False)),
                ('hasthumbup', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '吐槽',
                'db_table': 'tb_spit',
            },
        ),
    ]
