# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-28 14:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0003_remove_reply_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, null=True, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='文章内容')),
                ('image', models.ImageField(default=None, null=True, upload_to='', verbose_name='文章封面')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期')),
                ('visits', models.IntegerField(default=0, null=True, verbose_name='浏览量')),
                ('thumbup', models.IntegerField(default=0, null=True, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, null=True, verbose_name='评论数')),
            ],
            options={
                'db_table': 'tb_article',
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True, verbose_name='频道名称')),
            ],
            options={
                'db_table': 'tb_channel',
                'verbose_name_plural': '频道',
                'verbose_name': '频道',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='回答内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Article', verbose_name='问题ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='article.Comment', verbose_name='父评论')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'ordering': ['-createtime'],
                'db_table': 'article_comment',
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.Channel', verbose_name='所属频道'),
        ),
        migrations.AddField(
            model_name='article',
            name='collected_users',
            field=models.ManyToManyField(related_name='collected_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(related_name='articles', to='question.Label'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
    ]
