# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='文章封面'),
        ),
    ]
