# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-10 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190928_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createtime'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
