# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-28 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20190928_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='nickname',
        ),
    ]
