# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_reply_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='type',
            field=models.IntegerField(default=0, verbose_name='回答类型'),
        ),
    ]
